
#print_head "Update MongoDB lisiting Address"
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf  ##update /etc/mongod.conf from 127.0.0.1 to 0.0.0.0
#status_check $?
#
#print_head "enabling mongodb"
#systemctl enable mongod &>>${log_file}
#status_check $?
#
#print_head "restart mongodb"
#systemctl restart mongod &>>${log_file}
#status_check $?
#
##update /etc/mongod.conf from 127.0.0.1 to 0.0.0.0


- name: Setup MongoDB YUM repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true