- name: Installing nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Removing Old Content(ansible removes directory-it cant delete html file)
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Downloading and Extracting Frontend Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copying roboshop Config in nginx
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

#- name: Start Nginx Service
#  ansible.builtin.service:
#    name: nginx
#    state: started
#    enabled: yes
