- name: Installing nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Removing Old Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: Downloading and Extracting Frontend Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

## Download from Nexus
- name: Download and Extract {{ component }} Content
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.user', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.pass', region='us-east-1') }}@nexus.devopsb72.online:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Create Config in Nginx
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Create roboshop Config in nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

#- name: Start Nginx Service
#  ansible.builtin.service:
#    name: nginx
#    state: started
#    enabled: yes
